---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  DBServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-942dd1f6
      InstanceType: t2.nano
      Monitoring: false
      Tags:
      - Key: Name
        Value: Database Server
      - Key: Owner
        Value: garyd
      - Key: Team
        Value: My Super Team
  DBServerAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: |-
        Alarm if CPU too high or metric disappears indicating instance is down
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref DBServer
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Period: 60
      Statistic: Average
      Threshold: 85
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-942dd1f6
      InstanceType: t2.micro
      Monitoring: false
      Tags:
      - Key: Name
        Value: Web Server
      - Key: Owner
        Value: garyd
      - Key: Team
        Value: My Super Team

